### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by eruizdechavez** [LetsZiggy/phpcbf-Formatter#1]
Not really an issue. Just wanted to write to say **THANK YOU** for publishing this. I've been testing all available plugins for days and even tried to fix one that look promising, but yours is the **only** one which actually works as intended (reading `.phpcs.xml` on the folder with no extra configurations).

👏🎉👏🎉👏🎉👏

**Comment by LetsZiggy** [comment]
@eruizdechavez
welcome. hopefully it serves u well 😁
